---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: websocket-echo
  template:
    metadata:
      labels:
        app: websocket-echo
    spec:
      containers:
      - name: websocket-echo
        image: linkous8/websocket-echo:latest
        imagePullPolicy: Always
        args:
        - "websocket_echo/app.py"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-echo
spec:
  type: ClusterIP
  selector:
    app: websocket-echo
  ports:
  - name: http
    port: 80
    targetPort: 80
